language: java
jdk:
- oraclejdk11
services:
- docker
env:
  matrix:
  - MAVEN_VERSION=3.3.9
install:
- mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}
script:
- mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: I+kLHFcoYTmJQjRqorBryQanCKIG/rXUZaQDcpoRHel6RNhiexbK/wYA2qKsub/U/9jb8DhOpZect0AeYbKKl4avE4TJJLYoeIY4X/QL0IP1rzUL80uGlNgPa9pqG5DSIWC3/WWkDlJ/iF3mfhA1yhY9wDfzV2mkPJ3F+3Q1Gfbc6u5IOfDUUxzkmDD//mrQRSr1OfBGfeEMyqhvDHcO7r/Voj3NrGIZG1U1DUGPOyQ91dMTWrVpnGx1TCLDi+1EAzUexiPc5qMJiF0T5zSTvPSEg7ISc0ctsUqoUwitxlNlMRCPFjJsjL77/RKZ0JYjzGxchfWMkALuAh/NzpFv22mmeeliSu9PUrFNoYa+mJ4SXWo3UUeTzcm6siqkyE4Ti58w61dnT9rmrY3RXvM+U+y9PIB4JjDHNuQTVdzi3I86RBDBoKPjBVrezByFYWsR9KCvWJeoG3R+I4lmI1LY88r4ogdXaeDmlSaFyxpwx1BF+QhoUV/PiI2lqipTdw+npr1bJllNu6a211JazvGOk4TOrSynvhE9SAK+Ko06udmJQs7321qxS486uDfOxkFT1MweNHWahx4tumaOYN8Yg4f+ANzEc1iY7wb3abI2x8UWHiGVBwljXIVWORVheDUu0MF3JLErpbmCIoocKZrzmYBO0rFgw+upezLNNBpdKZA=
  app: yahtzee-webserver
  on:
    repo: cjbreg/yahtzeeserver
  skip_cleanup: 'true'
