language: java
jdk:
- oraclejdk11
services:
- docker
env:
  matrix:
  - MAVEN_VERSION=3.3.9
install:
- mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}
script:
- mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: cOumPoELSITH8QFvE+QdSbp4DfGGtfpMmMUbaW53Rpo8W9iNzT65/yTCDhYExkivtlQAEZKxwg0CL+JkDTB0LabHHsjjfeg+5b7VUfMk10ozXBw47vh/n7D2Ja70Mx7DKllu+mF2A2W0w8p7gAxT3JGhxy749iFLTMCHWOyiyOGOr2WGaa73qMowvjfEZTpm0TOd04PhY/pZjaGgs58GZKiUdD2Qs4rOW0HrCy1zPbGc5xHxKKZjxioUZphfzw1KVOCv54vDfGCQRnKGuWZ/1fbi+9AIx4Dz7W0zi9L88v/c3JpreF9Osk8FqDIxmLOfReSZq/OJzl1xt0HuGVHfMD3vG0GEoSMwmkUB+DCS5d0yw2d0KHl6XowLBbggjcdBSOKj/EJ21nH2EaEmfi9oFFjYnsf0EWjpoqj2tYtN6lnh7PXSIk+4GRujzFXxudsmJcehhYFTJyWe+D+3xHwa9JG0dmPv+N8ScGuoAb9AzuSvdorXx13c5TaWRBPa7r1cFqvUo6CU3byL0SgIGGDGtH11KAo2FLBSZKU3LLiYXoey1kwzE5OCnMcyzQrTp2OufKoHNHnSMJ29qVbWZoDsxuQ6IRDDwqDeVrDaOZX+oAj7BTkxw4JC6Hs0ozFKcsVOizU3qgCHodG3DWk0sXSLC7QD+tztem4DlOyIzfO/o5w=
  app: yahtzee-server
  on:
    repo: cjbreg/YahtzeeServer
    branch: main
  skip_cleanup: 'true'
